"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { Deployment } from "@/types/deployment";

export function DashboardLive({ initialDeployments }: { initialDeployments: Deployment[] }) {
  const [deployments, setDeployments] = useState(initialDeployments);
  const [lastChecked, setLastChecked] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  async function refresh() { setLoading(true); try { const roleArn = localStorage.getItem("fieldline.roleArn"); const externalId = localStorage.getItem("fieldline.externalId") || undefined; const region = localStorage.getItem("fieldline.region"); const accessKeyId = localStorage.getItem("fieldline.accessKeyId") || undefined; const secretAccessKey = localStorage.getItem("fieldline.secretAccessKey") || undefined; const sessionToken = localStorage.getItem("fieldline.sessionToken") || undefined; if (!roleArn || !region || !accessKeyId || !secretAccessKey) { setDeployments([]); setMessage("Connect an AWS access key and role to discover deployments."); return; } const response = await fetch("/api/deployments/discover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ roleArn, externalId, region, accessKeyId, secretAccessKey, sessionToken }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Status check failed."); setDeployments(result.deployments); setMessage(""); setLastChecked(new Date().toLocaleTimeString()); } catch (error) { setMessage(error instanceof Error ? error.message : "Live status check failed."); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 600000); return () => window.clearInterval(timer); }, []);
  const instanceCount = deployments.reduce((total, deployment) => total + deployment.instances.length, 0);
  const readyCount = deployments.filter((deployment) => deployment.stage === "ready" || deployment.stage === "infrastructure-ready").length;
  return <main className="min-h-screen bg-[#f4f7f5] p-6 text-[#173b42] md:p-12"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#438276]">Fieldline / Dashboard</p><h1 className="mt-3 font-[family-name:var(--font-space)] text-4xl font-semibold">Your deployments</h1><p className="mt-2 text-xs text-[#8ba099]">Live status checked every 10 minutes · Last checked {lastChecked || "Checking now..."}</p></div><Link className="rounded bg-[#0d766f] px-4 py-3 text-sm font-semibold text-white" href="/create">+ Create deployment</Link></header>{message && <div className="mt-5 rounded border border-[#d7e8e1] bg-white p-3 text-sm text-[#397b6c]">{message}</div>}<div className="mt-8 grid gap-4 md:grid-cols-3"><Metric label="Deployments found" value={deployments.length} /><Metric label="Infrastructure ready" value={readyCount} /><Metric label="Tracked instances" value={instanceCount} /></div><section className="mt-8 rounded-lg border border-[#d8e5df] bg-white"><div className="border-b border-[#edf2ef] p-5"><h2 className="font-semibold">Existing deployments</h2><p className="mt-1 text-xs text-[#71837c]">Open a deployment to start, stop, or terminate its servers.</p></div>{loading ? <div className="flex items-center justify-center gap-3 p-10 text-sm text-[#71837c]"><span className="size-4 animate-spin rounded-full border-2 border-[#b9d8ce] border-t-[#0d766f]" />Checking AWS deployments...</div> : deployments.length === 0 ? <div className="p-8 text-center text-sm text-[#71837c]">No deployments found.</div> : deployments.map((deployment) => <Link className="flex flex-wrap items-center justify-between gap-4 border-b border-[#edf2ef] p-5 last:border-0 hover:bg-[#f8fbf9]" href={`/deployments/${deployment.deploymentId}`} key={deployment.deploymentId}><div><strong className="block hover:text-[#0d766f]">{deployment.environment === "cluster" ? "Splunk Cluster" : "Splunk Standalone"}</strong><span className="text-sm text-[#71837c]">{deployment.region} · {deployment.deploymentId} · {deployment.instances.length} instances</span></div><span className="rounded-full bg-[#e5f5ee] px-3 py-1 text-[10px] font-semibold text-[#38836c]">{deployment.stage.toUpperCase()} →</span></Link>)}</section></div></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border border-[#d8e5df] bg-white p-5"><span className="text-xs text-[#71837c]">{label}</span><strong className="mt-2 block text-xl">{value}</strong></div>; }
