"use client";

import { useEffect, useState } from "react";
import { DeploymentInstanceControls } from "@/components/deployment/DeploymentInstanceControls";
import type { Deployment } from "@/types/deployment";

export function DeploymentDetailsLive({ deploymentId }: { deploymentId: string }) {
  const [deployment, setDeployment] = useState<Deployment | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { const roleArn = localStorage.getItem("fieldline.roleArn"); const externalId = localStorage.getItem("fieldline.externalId") || undefined; const region = localStorage.getItem("fieldline.region"); const accessKeyId = localStorage.getItem("fieldline.accessKeyId") || undefined; const secretAccessKey = localStorage.getItem("fieldline.secretAccessKey") || undefined; const sessionToken = localStorage.getItem("fieldline.sessionToken") || undefined; if (!roleArn || !region || !accessKeyId || !secretAccessKey) { setError("Connect the AWS access key and role in this browser before opening deployment details."); return; } fetch("/api/deployments/discover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ roleArn, externalId, region, accessKeyId, secretAccessKey, sessionToken, deploymentId }) }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load deployment from AWS."); const found = result.deployments?.[0] as Deployment | undefined; if (!found) throw new Error("This deployment was not found in the connected AWS account."); setDeployment(found); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load deployment from AWS.")); }, [deploymentId]);
  if (error) return <div className="mt-8 rounded border border-[#edc7c1] bg-[#fff2ef] p-5 text-sm text-[#b95548]">{error}</div>;
  if (!deployment) return <div className="mt-8 flex items-center gap-3 rounded border border-[#d8e5df] bg-white p-8 text-sm text-[#71837c]"><span className="size-4 animate-spin rounded-full border-2 border-[#b9d8ce] border-t-[#0d766f]" />Loading deployment from AWS...</div>;
  return <><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-[#438276]">Deployment details</p><h1 className="mt-3 font-[family-name:var(--font-space)] text-4xl font-semibold">{deployment.environment === "cluster" ? "Splunk Cluster" : "Splunk Standalone"}</h1><p className="mt-2 font-mono text-xs text-[#71837c]">{deployment.deploymentId} · AWS account {deployment.accountId} · {deployment.region}</p></div><div className="flex gap-3"><button className="rounded border border-[#cadbd4] bg-white px-4 py-3 text-sm">Configure manually</button><button className="rounded bg-[#0d766f] px-4 py-3 text-sm font-semibold text-white">Configure automatically</button></div></div><section className="mt-8 rounded-lg border border-[#d8e5df] bg-white p-5"><h2 className="font-semibold">Infrastructure status</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{[["AWS account", deployment.accountId],["VPC", deployment.vpcId ?? "Not returned"],["Subnet", deployment.subnetId ?? "Not returned"],["Stage", deployment.stage]].map(([label,value]) => <div className="rounded border border-[#edf2ef] p-4" key={label}><span className="block text-xs text-[#71837c]">{label}</span><strong className="mt-2 block text-sm">{value}</strong></div>)}</div></section><section className="mt-6 rounded-lg border border-[#d8e5df] bg-white p-5"><h2 className="font-semibold">EC2 instances</h2><p className="mt-1 text-xs text-[#71837c]">Live AWS status and server controls for this deployment.</p><DeploymentInstanceControls deploymentId={deploymentId} initialInstances={deployment.instances} /></section></>;
}
