"use client";

import { useEffect, useState } from "react";
import type { DeploymentInstance } from "@/types/deployment";

type Action = "start" | "stop" | "terminate";
export function DeploymentInstanceControls({ deploymentId, initialInstances }: { deploymentId: string; initialInstances: DeploymentInstance[] }) {
  const [instances, setInstances] = useState(initialInstances);
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");
  function savedCredentials() { return { region: localStorage.getItem("fieldline.region") || undefined, accessKeyId: localStorage.getItem("fieldline.accessKeyId") || undefined, secretAccessKey: localStorage.getItem("fieldline.secretAccessKey") || undefined, sessionToken: localStorage.getItem("fieldline.sessionToken") || undefined }; }
  async function refresh() { const params = new URLSearchParams({ deploymentId, ...Object.fromEntries(Object.entries(savedCredentials()).filter(([, value]) => value)) }); const response = await fetch(`/api/deployments/instances?${params}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to refresh instance status."); setInstances(result.instances); }
  useEffect(() => { void refresh().catch((error) => setMessage(error instanceof Error ? error.message : "Unable to refresh instance status.")); }, []);
  async function changeState(instance: DeploymentInstance, action: Action) { if (action === "terminate" && !window.confirm(`Terminate ${instance.name}? This cannot be undone.`)) return; setBusy(`${instance.instanceId}:${action}`); setMessage(""); try { const response = await fetch("/api/deployments/instances", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ deploymentId, instanceId: instance.instanceId, action, ...savedCredentials() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Instance action failed."); setInstances(result.instances); setMessage(`${instance.name}: ${action} request sent.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Instance action failed."); } finally { setBusy(""); } }
  return <>{message && <p className="mt-4 rounded border border-[#d7e8e1] bg-[#f2faf7] p-3 text-sm text-[#397b6c]">{message}</p>}{instances.length === 0 ? <p className="mt-4 text-sm text-[#b0782c]">No live instances were returned by AWS.</p> : <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-[#8ba099]"><tr><th className="py-3">Name</th><th>Role</th><th>Instance ID</th><th>Private IP</th><th>Public IP</th><th>State</th><th>Controls</th></tr></thead><tbody>{instances.map((instance) => { const action = instance.state === "stopped" ? "start" : "stop"; return <tr className="border-t border-[#edf2ef]" key={instance.instanceId}><td className="py-4 font-medium">{instance.name}</td><td>{instance.role}</td><td className="font-mono text-xs">{instance.instanceId}</td><td className="font-mono text-xs">{instance.privateIp ?? "-"}</td><td className="font-mono text-xs">{instance.publicIp ?? "-"}</td><td className="text-[#38836c]">● {instance.state}</td><td><div className="flex gap-2"><button disabled={Boolean(busy) || instance.state === "terminated"} onClick={() => void changeState(instance, action)} className="rounded border border-[#cadbd4] px-2 py-1 text-xs text-[#397b6c] disabled:opacity-50">{busy === `${instance.instanceId}:${action}` ? "Working..." : action === "start" ? "Start" : "Stop"}</button>{instance.state !== "terminated" && <button disabled={Boolean(busy)} onClick={() => void changeState(instance, "terminate")} className="rounded border border-[#edc7c1] px-2 py-1 text-xs text-[#b95548] disabled:opacity-50">{busy === `${instance.instanceId}:terminate` ? "Working..." : "Terminate"}</button>}</div></td></tr>; })}</tbody></table></div>}</>;
}
